### ISSUE TITLE
Can't read a simple ini file

### ISSUE THREAD

**Issue by pcn** [jonase/clojure-ini#2]
I can't read a simple ini file with clojure 1.5.1:

```
carbon-relaj.core=> (slurp "/opt/graphite/conf/relaj.conf")
"[default]\nspool_dir=/opt/graphite/spool\n"
carbon-relaj.core=> (ini/read-ini "/opt/graphite/conf/relaj.conf" :comment-char "#")
ClassCastException java.lang.String cannot be cast to java.lang.Character  clojure.lang.RT.intCast (RT.java:1087)
```

**Comment by pcn** [comment]
Actually, cloning this repo and running "lein test" failed too :frowning:

**Comment by jonase** [comment]
Thanks for the report. I'll take a look at this later today.

**Comment by jonase** [comment]
The argument to `:comment-char` should be a **char** and not a **string**:

```
(ini/read-ini "/opt/graphite/conf/relaj.conf" :comment-char \#)
```

**Comment by jonase** [comment]
@pcn I pushed version 0.0.2 to clojars. This version has a :pre condition that checks that `:comment-char` is a character.

**Comment by pcn** [comment]
Well color me :blush: for not noticing the type.

Thanks.
